language: python
python:
  - "2.6"
  - "2.7"
notifications:
	email:
		recipients:
			- zblanco@hortonworks.com
		on_success: never
		on_failure: always


# command to install dependencies
install: "pip install nose"
# command to run tests
script: nosetests -w tests