language: python
python:
  - "2.6"
  - "2.7"
notifications:
 email:
  recipients:
   - zblanco@hortonworks.com
  on_success: never
  on_failure: always


# command to install dependencies
install: 
 - pip install -r requirements.txt
 - pip install -r demo_app/requirements.txt
 - pip install coveralls
 
# command to run tests
script:
 - cd demo_app/
 - nosetests -w tests/
 - cd ../demo_utils
 - nosetests --with-coverage -w tests/
 - 
 
after_success:
 coveralls